[package]
name = "jt-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
mesh-tools = "0.4.0"
byteorder = "1.5"
anyhow = "1.0"
flate2 = "1.0"
uuid = { version = "1.10", features = ["v4"] }
clap = { version = "4.5", features = ["derive"] }
